# Generated by Django 4.1.3 on 2022-12-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bankroll_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankroll',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankroll',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
    ]
