# Generated by Django 4.1.3 on 2022-12-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bankroll_initial_balance_bankroll_profit_bet_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankroll',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
