# Generated by Django 4.1.3 on 2022-12-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bankroll_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
