# Generated by Django 4.1.3 on 2022-12-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bet_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
