# Generated by Django 4.1.3 on 2022-12-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_bet_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
