# Generated by Django 4.1.3 on 2022-12-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_bet_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankroll',
            name='loss_count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bankroll',
            name='win_count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
